LINKPATH=$(ANDROID_NDK)/platforms/android-9/arch-arm/usr/lib
INCLUDEPATH=$(ANDROID_NDK)/platforms/android-9/arch-arm/usr/include
CFLAGS=-Wall -g -Wl,-rpath-link=$(LINKPATH) -L$(LINKPATH) -I$(INCLUDEPATH) -nostdlib $(LINKPATH)/crtbegin_dynamic.o -lc
CC=arm-linux-androideabi-gcc
LD=arm-linux-androideabi-ld
AR=arm-linux-androideabi-ar

all: vm
	cp vm ../vm

vm: object.o instruction.o registers.o runtime.o vmmethod.o machine.o slot.o gc.o util.o

clean:
	rm -f ../vm vm
	rm -f *.o
	rm -fR *.dSYM
